
# DATA PREP
# Undersampling
undersampling: 0

# Oversampling
oversampling: 1
os_strategy: SMOTE # [SMOTE, random]
smote_ratio: 1.0

# Grid Search
grid_search: 1
gs_random: 0
gs_search_iter: 5
gs_num_folds: 3
gs_save_params: 1 # 1: yes, 0: no

# Plotting
save_plots: 1 # 1: yes, 0: no

# Participant Leakage
no_participant_leakage: 1

# Training
cross_validation: 0
cv_count: 15

# Neural Network
model_name: nn_model_1
batch_size: 32
epochs: 100
learning_rate: 0.001