# Database Name
database_name: 'flanker_data_12_02_01_24_15_30_25.pkl' # 'flanker_data_10-4_5-_30_12_23_17_22_11.pkl'
data_split: 0.8

# DATA PREP
# Undersampling
undersampling: 0    # 1

# Oversampling
oversampling: 1
os_strategy: SMOTE # [SMOTE, random]
smote_ratio: 0.5

# Grid Search
grid_search: 1
gs_random: 0
gs_search_iter: 5
gs_num_folds: 3
gs_save_params: 1 # 1: yes, 0: no

# Plotting
save_plots: 1 # 1: yes, 0: no

# Participant Leakage
no_participant_leakage: 1

# Training
cross_validation: 0
cv_count: 15

# Neural Network
model_name: nn_model_1    #BEST: 0.5601410934744269
batch_size: 368            # 100
epochs: 75                # 50
learning_rate: 0.005084237414519601     # 0.0003
K: 91                     # 90
fc_hidden_size: 1024       # 128
optimizer: Adam   # [Adam, Adagrad]         # Adam
batch_norm: 1             # 1
activation: leaky_relu          # relu, elu, selu, leaky_relu
dropout_prob: 0.3         # 0
psd_usage: 0               # 0

# # Neural Network
# model_name: nn_model_1    #BEST: 0.5601410934744269
# batch_size: 638            # 100
# epochs: 41                # 50
# learning_rate: 0.0073341     # 0.0003
# K: 87                     # 90
# fc_hidden_size: 712       # 128
# optimizer: Adagrad   # [Adam, Adagrad]         # Adam
# psd_usage: 0               # 0

# Transformer Parameters
tr_optuna: 0 # Enable optuna search
tr_optuna_trials: 30
tr_model_name: tr_model_1                 
tr_batch_size: 38
tr_epochs: 1500
tr_learning_rate: 0.0004970551888512231 #0.0002                  
tr_c_dim: 2                               
tr_b1: 0.7561626355615126 #0.5                                
tr_b2: 0.9364485902864262 #0.999                              
tr_emb_size: 20                           
tr_depth: 4                               
tr_n_classes: 1                           
tr_num_heads: 10
tr_drop_p: 0.5
tr_forward_expansion: 4
tr_forward_drop_p: 0.5
tr_save_model_every_n_epoch: 1


